{% set version = "30.2026.2300" %}
{% set python_min = "3.11.0" %}

package:
  name: lsst-resources
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lsst-resources/lsst_resources-{{ version }}.tar.gz
  sha256: 3e2ff4e19bcdfd23886cd5edfd62133359edf2189b494aee45169e9c71a61b62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - lsst-versions >=1.3.0
    - pip
  run:
    - python >={{ python_min }}
    - lsst-utils
    - backoff >=1.10
    - boto3 >=1.13
    - botocore >=1.15
    - requests >=2.26.0
    - moto >5.0.3

test:
  imports:
    - lsst
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lsst/resources
  summary: An abstraction layer for reading and writing from URI file resources.
  dev_url: https://github.com/lsst/resources
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - COPYRIGHT

extra:
  recipe-maintainers:
    - roceb
    - rhiannonlynne
    - timj
